# Generated by Django 4.2.5 on 2023-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
