# Generated by Django 4.2.5 on 2023-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_api', '0002_alter_bookingmodel_user_alter_fieldmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
