# Generated by Django 4.2.5 on 2023-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_api', '0003_rename_data_bookingmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmodel',
            name='price_frtoh',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
