# Generated by Django 4.2.5 on 2023-09-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_api', '0003_alter_bookingmodel_date_alter_bookingmodel_end_time_and_more'),
        ('field_api', '0004_fieldmodel_price_frtoh'),
    ]

    operations = [
    ]
